// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8WIb3hOH1bdQNc7IsZVwy1cvxou8hEhk',
    appId: '1:188702930872:web:77b3252a6ce6863308414d',
    messagingSenderId: '188702930872',
    projectId: 'mitra-348d9',
    authDomain: 'mitra-348d9.firebaseapp.com',
    storageBucket: 'mitra-348d9.firebasestorage.app',
    measurementId: 'G-BEKE245GYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjnz-L1M6pf1lpIJw0heXT82dIPa5BTCo',
    appId: '1:188702930872:android:bcd4c97d8ecd020b08414d',
    messagingSenderId: '188702930872',
    projectId: 'mitra-348d9',
    storageBucket: 'mitra-348d9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgbOsllP6sR8b8Nox8DX-egtwo6IFbeDA',
    appId: '1:188702930872:ios:c67d03c80820770808414d',
    messagingSenderId: '188702930872',
    projectId: 'mitra-348d9',
    storageBucket: 'mitra-348d9.firebasestorage.app',
    iosBundleId: 'com.mitra.ai.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgbOsllP6sR8b8Nox8DX-egtwo6IFbeDA',
    appId: '1:188702930872:ios:c67d03c80820770808414d',
    messagingSenderId: '188702930872',
    projectId: 'mitra-348d9',
    storageBucket: 'mitra-348d9.firebasestorage.app',
    iosBundleId: 'com.mitra.ai.app',
  );
}